# Generated by Django 4.2 on 2024-06-03 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='ClientName', max_length=50)),
                ('surname', models.CharField(db_column='ClientSurname', max_length=50)),
                ('email', models.EmailField(db_column='ClientEmail', max_length=254)),
                ('tg_name', models.CharField(db_column='ClientTg', max_length=255)),
                ('first_date', models.DateTimeField(auto_now=True, db_column='FirstDate')),
                ('update_date', models.DateTimeField(auto_now_add=True, db_column='UpdateDate')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'db_table': 'Service',
            },
        ),
        migrations.CreateModel(
            name='ServiceCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(db_column='ServiceName', max_length=50, unique=True)),
                ('slug_name', models.SlugField(db_column='SlugName', max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Вид услуги',
                'verbose_name_plural': 'Вид услуг',
                'db_table': 'ServiceCatalog',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(db_column='StatusName', max_length=255)),
            ],
            options={
                'verbose_name': 'Статус услуги',
                'verbose_name_plural': 'Статус услуг',
                'db_table': 'Status',
            },
        ),
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_price', models.DecimalField(blank=True, db_column='ServicePrice', decimal_places=2, max_digits=7)),
                ('service_client', models.ForeignKey(db_column='ClientID', on_delete=django.db.models.deletion.CASCADE, to='works.client')),
                ('service_name', models.ForeignKey(db_column='ServiceNameID', on_delete=django.db.models.deletion.CASCADE, to='works.servicecatalog')),
            ],
            options={
                'verbose_name': 'Цена услуги',
                'verbose_name_plural': 'Цены услуг',
                'db_table': 'ServicePrice',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='check_status',
            field=models.ForeignKey(db_column='ClientStatus', on_delete=django.db.models.deletion.CASCADE, to='works.status'),
        ),
        migrations.AddField(
            model_name='client',
            name='price',
            field=models.ManyToManyField(db_column='ServicePriceID', related_name='Client', through='works.ServicePrice', to='works.servicecatalog'),
        ),
        migrations.AddField(
            model_name='client',
            name='service',
            field=models.ForeignKey(db_column='ServiceNameID', on_delete=django.db.models.deletion.CASCADE, to='works.servicecatalog'),
        ),
    ]
